#baseURL = "http://andrewzm.github.io"
baseURL = "http://andrewzm.github.io/deepspat-website" # local environment has trouble because of the subdomain; change it back for local development.
languageCode = "en-us"
title = "Deep Learning for Spatial and Spatio-Temporal Statistics"
theme = "bigspring-light"
publishDir = "docs"
disablePathToLower = true # Do not convert the url/path to lowercase.



# Set menu buttons all at once like this (they can also be set individually
# using a different notation, but I think this is cleanest).
# Note that "weight" controls the position of the menu items; if it is not
# provided, the menu is sorted alphabetically.
[Menus]
  main = [
      {Name = "Home", url = "", identifier = "home", weight = 1},
      {Name = "Collaborators and Students", url = "collaborators/", identifier = "collaborators", weight = 3},
      {Name = "Publications", url = "outputs/", identifier = "outputs", weight = 4},
      {Name = "Workshop", url = "workshop/", identifier = "workshop", weight = 5},
      {Name = "Contact", url = "contact/", identifier = "contact", weight = 6},
      #{Name = "Github", URL = "https://github.com/andrewzm/"},
      #{Name = "Email", URL = "mailto:azm@uow.edu.au"}
  ]
  footer_left = [
    {name = "R Deepspat package", url = "https://github.com/andrewzm/deepspat", weight = 1},
    {name = "Centre for Environmental Informatics, University of Wollongong", url = "https://www.uow.edu.au/niasra/our-research/centre-for-environmental-informatics/", weight = 2},
    {name = "Australian Research Council", url = "https://www.arc.gov.au/", weight = 3},
  ]


[params]
  description = "DeepSpat description"
  author = "Andrew Zammit-Mangion"
  logo = "images/NIASRA-UOW.png"
  logo_width = "400px"
  link = "https://www.uow.edu.au/niasra/"
  ########### footer content ##########
  Copyright = "Copyright © 2022 [**Andrew Zammit-Mangion**](https://andrewzm.wordpress.com). This site was built with [**Hugo**](https://gohugo.io/) with the help of [**Matthew Sainsbury-Dale**](https://github.com/msainsburydale)."
  social = [
    {title = "twitter", icon = "fab fa-twitter", link = "https://twitter.com/andrewzm"},
    {title = "linkedin", icon = "fab fa-linkedin", link = "https://au.linkedin.com/in/andrewzammitmangion"},
  ]
  footer_menu_left = "Related links"
#  footer_content = "#### Social Media"
